name: Nightly-build

on:
  push:
    branches: [ "dev-nightly" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version:  ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Restore nuget packages
      run: nuget restore
    - name: Build client and installer
      run: dotnet build RageCoop.Client.Installer/RageCoop.Client.Installer.csproj --configuration Release -o bin/Release/Client/RageCoop
    - name: Build server win-x64
      run: dotnet publish RageCoop.Server/RageCoop.Server.csproj --self-contained -p:PublishSingleFile=true -p:PublishTrimmed=false -r win-x64 -o bin/Release/Server/win-x64 -c Release
    - name: Build server linux-x64
      run: dotnet publish RageCoop.Server/RageCoop.Server.csproj --self-contained -p:PublishSingleFile=true -p:PublishTrimmed=false -r linux-x64 -o bin/Release/Server/linux-x64 -c Release
    - uses: vimtor/action-zip@v1
      with:
        files: bin/Release/Client
        dest: RageCoop.Client.zip

    - uses: vimtor/action-zip@v1
      with:
        files: bin/Release/Server/win-x64
        dest: RageCoop.Server-win-x64.zip

    - uses: vimtor/action-zip@v1
      with:
        files: bin/Release/Server/linux-x64
        dest: RageCoop.Server-linux-x64.zip

    - name: Publish nightly release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: nightly
        name: Nightly build
        prerelease: true
        target_commitish: ${{ github.sha }}
        files: |
          RageCoop.Client.zip
          RageCoop.Server-win-x64.zip
          RageCoop.Server-linux-x64.zip
